apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ldy230tqu-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-91cbee932c.ly4a.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:020e9a512a9ff153629d31c14e3d71e8ca4a4651@sha256:00eadffe23c59ecf5004dfea4aa4403ddfc36cd5598dd5ca7392360be78af252
          name: container-image
